services:
  # Development service
  piglmayer-website-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piglmayer-website-prod
    ports:
      - '30023:30023'
    environment:
      - NODE_ENV=production
    networks:
      - leb-network

networks:
  leb-network:
    driver: bridge
