services:
  # Development service
  piglmayer-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piglmayer-dev
    ports:
      - '30023:30023'
    environment:
      - NODE_ENV=development
